import type { Metadata } from "next";
import { Poppins, Lora, Averia_Libre, Grandstander } from "next/font/google";
import localFont from "next/font/local";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";

// font google
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-poppins",
});

const lora = Lora({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-lora",
  style: ["normal", "italic"],
});

const averiaLibre = Averia_Libre({
  subsets: ['latin'],
  weight: ['400','700'],
  variable: '--font-averia',
})

const grandstander = Grandstander({
  subsets: ['latin'],
  weight: ['400','700'],
  variable: '--font-grandstander',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Imperial+Script&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={`${poppins.variable} ${lora.variable} ${averiaLibre.variable} ${grandstander.variable}`}>
        {children}
      </body>
    </html>
  );
}